import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { readSkillDefaults, updateSkillDefaults, updateGlobalSkillDefaults } from '../lib/task-context-store.mjs';

const home = mkdtempSync(join(tmpdir(), 'scoped-defaults-'));
const id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const none = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
const root = join(home, 'demo-project'), nested = join(root, 'nested');
const global = '默认执行 · 通用约定', project = '默认执行 · 项目约定';
try {
  mkdirSync(nested, { recursive: true });
  const file = join(home, 'skill-defaults.json');
  writeFileSync(file, JSON.stringify({ defaults: [global], extra: true, projects: { p: { defaults: [project], extra: 1 }, n: { defaults: [] } } }));
  const state = { 'local-projects': { p: { name: '项目', rootPaths: [root] }, n: { name: '子项目', rootPaths: [nested] } }, 'thread-project-assignments': { [id]: { projectKind: 'local', projectId: 'p' } }, 'projectless-thread-ids': [none] };
  const stateFile = join(home, '.codex-global-state.json');
  writeFileSync(stateFile, JSON.stringify(state));
  const options = { codexHome: home, threadId: id, cwd: home };
  assert.deepEqual(readSkillDefaults(options).projectSkillDefaults, [project]);
  assert.equal(readSkillDefaults({ codexHome: home, cwd: nested }).skillDefaultsProject.projectId, 'n');
  assert.equal(readSkillDefaults({ codexHome: home, cwd: root + '-other' }).skillDefaultsProject, null);
  assert.equal(readSkillDefaults({ codexHome: home, threadId: none, cwd: root }).skillDefaultsProject, null);
  assert.equal(readSkillDefaults({ codexHome: home, cwd: home }).skillDefaultsProject, null);
  state['thread-project-assignments'][id].projectId = 'missing';
  writeFileSync(stateFile, JSON.stringify(state));
  assert.equal(readSkillDefaults({ ...options, cwd: root }).skillDefaultsProject, null);
  state['thread-project-assignments'][id] = null;
  writeFileSync(stateFile, JSON.stringify(state));
  assert.equal(readSkillDefaults({ ...options, cwd: root }).skillDefaultsProject, null);
  state['thread-project-assignments'][id] = { projectKind: 'local', projectId: 'p' };
  writeFileSync(stateFile, JSON.stringify(state));
  const skill = join(home, 'SKILL.md'); writeFileSync(skill, '# Test');
  const entry = { name: 'test', title: 'Test', path: skill };
  updateGlobalSkillDefaults({ codexHome: home, action: 'add', entry });
  assert.equal(JSON.parse(readFileSync(file)).extra, true);
  assert.equal(JSON.parse(readFileSync(file)).projects.p.extra, 1);
  const added = updateSkillDefaults({ ...options, scope: 'project', projectId: 'p', action: 'add', entry });
  assert.equal(added.projectSkillDefaults.length, 2);
  updateSkillDefaults({ ...options, scope: 'global', action: 'remove', value: added.globalSkillDefaults[1] });
  assert.equal(readSkillDefaults(options).projectSkillDefaults.length, 2);
  updateSkillDefaults({ ...options, scope: 'project', projectId: 'p', action: 'remove', value: added.projectSkillDefaults[1] });
  assert.deepEqual(readSkillDefaults(options).globalSkillDefaults, [global]);
  assert.throws(() => updateSkillDefaults({ ...options, scope: 'project', projectId: 'n', action: 'add', entry }));
  const script = fileURLToPath(new URL('../scripts/task-context-guard.mjs', import.meta.url));
  const run = (args, input, threadId = id) => {
    const result = spawnSync(process.execPath, [script, ...args], { encoding: 'utf8', cwd: home, env: { ...process.env, CODEX_HOME: home, CODEX_THREAD_ID: threadId, LOCALAPPDATA: home }, input: input && JSON.stringify(input) });
    assert.equal(result.status, 0, result.stderr); return result.stdout;
  };
  assert.equal(run(['--defaults', '--cwd', home]).trim(), [global, project].join('\n'));
  assert.equal(run(['--defaults', '--cwd', root], null, '').trim(), [global, project].join('\n'));
  assert.equal(run(['--defaults', '--cwd', root], null, none).trim(), global);
  const event = { session_id: id, cwd: home, hook_event_name: 'UserPromptSubmit', turn_id: 'test' };
  const injected = JSON.parse(run([], event)).hookSpecificOutput.additionalContext;
  assert(injected.includes(global) && injected.includes(project) && injected.includes('当前项目默认设置（项目）'));
  assert.equal(run([], { ...event, hook_event_name: 'Stop' }), '');
  console.log('scoped skill defaults checks passed');
} finally { rmSync(home, { recursive: true, force: true }); }
