import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { resolveTaskReferences } from '../lib/task-references.mjs';
const id = '11111111-1111-4111-8111-111111111111';

test('task references join exact provenance, stay bounded and refresh without loading source content', t => {
  const root = mkdtempSync(path.join(os.tmpdir(), 'task-links-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const old = '33333333-3333-4333-8333-333333333333';
  const write = (file, value) => writeFileSync(path.join(root, file), JSON.stringify(value));
  const bindings = '.thread-project-bindings.json', tickets = '.generation-tickets.json';
  write(bindings, { bindings: { [id]: { projectId: 'current', projectName: '当前项目' }, other: { projectId: 'other' } } });
  const ticket = (source, name) => ({ id: name, projectId: 'current', sourceContext: { threadId: source }, prompt: 'NOT_IN_SUMMARY', outputs: [{ id: name + '-output', path: `E:/assets/${name}.png`, archivedAt: '2026-09-06T00:00:00Z' }] });
  write(tickets, { tickets: [ticket(id, 'now'), ticket(old, 'before'), ticket('unrelated', 'same-project')] });
  const context = { threadId: id, references: [{ kind: 'history', archivePath: 'E:/frozen/archive', recordId: 18156, sourceThreadId: old }, { kind: 'asset', path: 'E:/local/preview.html' }, { kind: 'asset', path: 'relative.png' }, { kind: 'history', archivePath: 'E:/wrong\npath' }] };
  const result = resolveTaskReferences(context, root);
  assert.deepEqual(result.assetBinding, { projectId: 'current', projectName: '当前项目' });
  assert.equal(result.referenceStatus, '');
  assert.equal(result.references.length, 4);
  assert.deepEqual(result.references.slice(2).map(ref => ref.ticketId), ['now', 'before']);
  assert.equal(result.references[2].sourceThreadId, id);
  assert.doesNotMatch(JSON.stringify(result), /NOT_IN_SUMMARY|same-project|unrelated/);
  assert.equal(result.references[0].recordId, 18156);
  const otherTask = resolveTaskReferences({ threadId: old }, root);
  assert.equal(otherTask.assetBinding, null);
  assert.deepEqual(otherTask.references.map(ref => ref.ticketId), ['before']);
  assert.deepEqual(resolveTaskReferences({ ...context, threadId: 'invalid' }, root), {});
  assert.equal(resolveTaskReferences({ threadId: id }, root).references.length, 1, 'old task must be explicitly linked');
  assert.deepEqual(resolveTaskReferences(context, root), result, 'cached result keeps all metadata');
  write(bindings, { bindings: { [id]: { projectId: 'changed-project' } } });
  write(tickets, { tickets: Array.from({ length: 10 }, (_, i) => ticket(id, `new-${i}`)) });
  assert.equal(resolveTaskReferences(context, root).assetBinding.projectId, 'changed-project');
  assert.equal(resolveTaskReferences(context, root).references.length, 8, 'at most six auto outputs');
  writeFileSync(path.join(root, bindings), '{broken');
  writeFileSync(path.join(root, tickets), '{broken');
  const broken = resolveTaskReferences(context, root);
  assert.equal(broken.references.length, 2);
  assert.equal(broken.assetBinding, null);
  assert.match(broken.referenceStatus, /绑定读取失败.*来源索引读取失败/);
  const empty = path.join(root, 'empty'); mkdirSync(empty);
  assert.equal(resolveTaskReferences(context, empty).referenceStatus, '');
  assert.equal(resolveTaskReferences(context, empty).references.length, 2);
});
